# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # https://stackoverflow.com/questions/73693257/how-to-fix-could-not-find-system-library-libudev-when-installing-cargo-flash
      - name: Prepare
        run: echo "Installing dependencies" && sudo apt install -y pkg-config libusb-1.0-0-dev libftdi1-dev libudev-dev

      # Runs a single command using the runners shell
      - name: Build
        run: echo "Building project on Ubuntu version $(lsb_release -ds)" && cargo build --manifest-path gq_gmc/Cargo.toml && cargo test --manifest-path gq_gmc/Cargo.toml